package interface_adaptors.FinancialReport;

import use_case.FinancialReport.FinancialReportOutputBoundary;
import use_case.FinancialReport.FinancialReportOutputData;

/**
 * The FinancialReportPresenter class implements the output boundary to present the report.
 *
 * This class is responsible for displaying the financial report generated by the interactor.
 * It stores the report content and provides a method to retrieve it for testing purposes.
 *
 * Author: Chi Fong Huang
 */
public class FinancialReportPresenter implements FinancialReportOutputBoundary {
    private String reportContent;

    /**
     * Presents the financial report by storing its content and printing it to the console.
     *
     * This method is called by the interactor to deliver the generated financial report.
     *
     * @param outputData the output data containing the report content
     */
    @Override
    public void presentReport(FinancialReportOutputData outputData) {
        this.reportContent = outputData.getReportContent();
        System.out.println(reportContent);
    }

    /**
     * Returns the content of the financial report.
     *
     * This method is primarily used for testing purposes to verify the report content.
     *
     * @return the content of the financial report
     */
    public String getReportContent() {
        return reportContent;
    }
}



